require "user.autorun"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.harpoon"
require "user.mason-config"
require "user.lsp-zero"
require "user.colorscheme"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.lualine"
require "user.indent"
require "user.colorizer"
require "user.ts-autotag"
require "user.treesitter-context"
require "user.symbols_outline"
require "user.wilder"
require "user.navbuddy"
require "user.luasnip"


